const drinkData = {
  drinks: [{
    idDrink: '12474',
    strDrink: 'Waikiki Beachcomber',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions: 'Shake all ingredients with ice, strain into a cocktail glass, and serve.',
    strInstructionsES: null,
    strInstructionsDE: 'Alle Zutaten mit Eis sch\u00fctteln, in ein Cocktailglas abseihen und servieren.',
    strInstructionsFR: null,
    strInstructionsIT: 'Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/ysuqus1441208583.jpg',
    strIngredient1: 'Triple sec',
    strIngredient2: 'Gin',
    strIngredient3: 'Pineapple juice',
    strIngredient4: null,
    strMeasure1: '3/4 oz ',
    strMeasure2: '3/4 oz ',
    strMeasure3: '1 tblsp ',
    strMeasure4: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2015-09-02 16:43:03',
  }],
};

export default drinkData;
